#
# Azure DevOps pipeline
#
# Description     : DevInfra Auto remove Test
# Created by      : Muhammed Iqbal
#
#


trigger:
  batch: true
  branches:
    include:
      - master
      - development
  paths:
    exclude:
      - README.md
      - LICENSE
      - .gitignore

# Don't run against PRs
pr: none

variables:
- group: terraform-vars

# Agent VM image name
- name: vmImageName
  value: 'ubuntu-latest'


stages:

  - stage: Test
    jobs:
      - template: templates/test.yml
        parameters:
          vmImage: $(vmImageName)

  - stage: Build
    displayName: Build
    jobs:

