#
# Azure DevOps pipeline
#
# Description     : DevInfra Auto remove Test
# Created by      : Muhammed Iqbal
#
#

trigger: none

#trigger:
#  batch: true
#  branches:
#    include:
#      - master
#      - development
#  paths:
#    exclude:
#      - README.md
#      - LICENSE
#      - .gitignore

# Don't run against PRs
pr: none

parameters:
- name: resource_ttl
  displayName: Resources Expiry Time
  type: string
  default: "1 hours"
  values:
  - "1 hours"
  - "4 hours"
  - "8 hours"
  - "1 day"
  - "2 days"
  - "7 days"


variables:
- group: terraform-vars


stages:
- stage: Validation
  displayName: Terraform config validation

  jobs:  
  - job: Validation
    displayName: Terraform config validate
    pool:
      vmImage: 'ubuntu-latest' 
    
    steps:
      - script: |
          echo "Parameter Value is ${{ parameters.resource_ttl }}"
          echo "Expiry time calculation"
          echo "======================="
          now=$(date)
          expiry_date=$(date "+%F-%H-%M-%S" --date='${{ parameters.resource_ttl }}')
          echo "final date"
          echo $expiry_date
      - task: TerraformInstaller@0
        displayName: Install
        inputs:
          terraformVersion: 'latest'
      
      - task: TerraformCLI@0
        displayName: Init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          commandOptions: '-backend=false'
          allowTelemetryCollection: false    
      
      - task: TerraformCLI@0
        displayName: Validate
        inputs:
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          allowTelemetryCollection: true

      
- stage: Provision
  displayName: Provision Infrastructure
  dependsOn: Validation
  #condition: and(succeeded(), ne(variables['action'], 'destroy'))
  condition: and(succeeded(), eq(variables['action'], 'destroy'))

  jobs:  
  - job: Provision
    displayName: Provision Infrastructure
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: TerraformInstaller@0
        displayName: Install 
        inputs:
          terraformVersion: 'latest'
      
      - task: TerraformCLI@0
        displayName: Init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          backendType: 'azurerm'
          backendServiceArm: 'mysubscription'
          backendAzureRmResourceGroupName: 'RG_iqbal_tests'
          backendAzureRmStorageAccountName: 'iquzartinfra'
          backendAzureRmContainerName: 'terraform-state'
          backendAzureRmKey: 'tstate-az-devops.state'
          allowTelemetryCollection: false
      
     
      - task: TerraformCLI@0
        displayName: Plan
        inputs:
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          environmentServiceName: 'mysubscription'
          secureVarsFile: 'terraform.tfvars'
          allowTelemetryCollection: false

      - task: TerraformCLI@0
        displayName: Apply
        inputs:
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          environmentServiceName: 'mysubscription'
          secureVarsFile: 'terraform.tfvars'
          allowTelemetryCollection: false

- stage: Destroy
  displayName: Destroy Infrastructure
  dependsOn: Validation
  condition: and(succeeded(), eq(variables['action'], 'destroy'))

  jobs:  
  - job: Destroy
    displayName: Destroy Infrastructure
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: TerraformInstaller@0
        displayName: Install 
        inputs:
          terraformVersion: 'latest'

      - task: TerraformCLI@0
        displayName: Init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          backendType: 'azurerm'
          backendServiceArm: 'mysubscription'
          backendAzureRmResourceGroupName: 'RG_iqbal_tests'
          backendAzureRmStorageAccountName: 'iquzartinfra'
          backendAzureRmContainerName: 'terraform-state'
          backendAzureRmKey: 'tstate-az-devops.state'
          allowTelemetryCollection: false

      - task: TerraformCLI@0
        displayName: Destroy
        inputs:
          command: 'destroy'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          environmentServiceName: 'mysubscription'
          secureVarsFile: 'terraform.tfvars'
          allowTelemetryCollection: false