#
# Azure DevOps pipeline
#
# Description     : DevInfra Auto remove Test
# Created by      : Muhammed Iqbal
#
#

#trigger: none
trigger:
  batch: true
  branches:
    include:
      - master
      - development
  paths:
    exclude:
      - README.md
      - LICENSE
      - .gitignore

# Don't run against PRs
pr: none

variables:
- group: terraform-vars

# Agent VM image name
- name: vmImageName
  value: 'ubuntu-latest'

- name: test
#  value: ''


stages:
- stage: Init
  displayName: Terraform Init

  jobs:  
  - job: InitJob
    displayName: Terraform Init Job
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: |
          echo "Checking the parameter variable"
          echo The variable Value: $(test)

      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      
      - task: TerraformCLI@0
        displayName: Terraform Init Job
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          backendType: 'azurerm'
          backendServiceArm: 'mysubscription'
          backendAzureRmResourceGroupName: 'RG_iqbal_tests'
          backendAzureRmStorageAccountName: 'iquzartinfra'
          backendAzureRmContainerName: 'terraform-state'
          backendAzureRmKey: 'tstate-az-devops.state'
          allowTelemetryCollection: false
      
      #- task: TerraformCLI@0
      #  inputs:
      ##    command: 'validate'
      #    workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
      #    secureVarsFile: 'terraform.tfvars'
      #    allowTelemetryCollection: true
      
      - task: TerraformCLI@0
        displayName: Terraform Plan Job
        inputs:
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          environmentServiceName: 'mysubscription'
          secureVarsFile: 'terraform.tfvars'
          allowTelemetryCollection: false

      - task: TerraformCLI@0
        displayName: Terraform Apply Job
        inputs:
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/go-app/terraform'
          environmentServiceName: 'mysubscription'
          secureVarsFile: 'terraform.tfvars'
          allowTelemetryCollection: false